Repository selsa-inube/inubekit-foundations, pull requests merged in 2024-02, with the labels that each got.

#25 feat: delete presente tokens and its export
  src/index.ts
  src/shared/themes/presente/colors/index.ts
  src/shared/themes/presente/colors/palette.ts
  src/shared/themes/presente/colors/stroke.ts
  src/shared/themes/presente/colors/surface.ts
  src/shared/themes/presente/colors/text.ts
  src/shared/themes/presente/index.ts
  src/shared/themes/presente/spacing/index.ts
  src/shared/themes/presente/typography/body.ts
  src/shared/themes/presente/typography/display.ts
  src/shared/themes/presente/typography/headline.ts
  src/shared/themes/presente/typography/index.ts
  src/shared/themes/presente/typography/label.ts
  src/shared/themes/presente/typography/title.ts
Labels: major

#26 feat: delete all current tokens with old structure
  src/index.ts
  src/shared/tokens/colors/index.ts
  src/shared/tokens/colors/palette.ts
  src/shared/tokens/colors/stroke.ts
  src/shared/tokens/colors/surface.ts
  src/shared/tokens/colors/text.ts
  src/shared/tokens/index.ts
  src/shared/tokens/spacing/index.ts
  src/shared/tokens/typography/body.ts
  src/shared/tokens/typography/display.ts
  src/shared/tokens/typography/headline.ts
  src/shared/tokens/typography/index.ts
  src/shared/tokens/typography/label.ts
  src/shared/tokens/typography/title.ts
  src/tokens/types/type.ts
Labels: major

#28 feat: create and export text tokens
  src/components/index.ts
  src/components/text.ts
Labels: major, minor

#29 feat: create and export icon tokens
  src/components/icon.ts
  src/components/index.ts
Labels: minor

#32 Create and export `<Fieldset />` tokens
  src/components/fieldset.ts
  src/components/index.ts
Labels: enhancement

#31 Create and export `<Spinner />` tokens
  package-lock.json
  src/components/index.ts
  src/components/spinner.ts
Labels: enhancement

#33 Publish new version
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#36 Create new Label tokens
  src/components/index.ts
  src/components/label.ts
Labels: enhancement, minor

#37 Create new Switch tokens
  src/components/index.ts
  src/components/switch.ts
Labels: enhancement, minor

#39 Adjust icon tokens to add background block and adjust content disabled
  src/components/icon.ts
Labels: patch

#41 Fix inube.text.light.content.color.regular
  src/components/text.ts
Labels: minor

#40 Release new version 2.2.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation, minor

#42 release new version 2.2.1
  CHANGELOG.md
  README.md
Labels: patch

#43 Update package.json with the latest version according to CHANGELOG
  package-lock.json
  package.json
Labels: documentation, dependencies

#44 Update Button tokens
  src/components/button.ts
Labels: minor

#45 Create and export input tokens
  src/components/index.ts
  src/components/input.ts
Labels: minor

#46 Publish new version 2.3.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#48 Publish new version 2.4.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation
