Repository selsa-inube/inubekit-foundations, pull requests merged in 2024-03, with the labels that each got.

#49 Add gray appearance in spinner tokens
  src/components/spinner.ts
Labels: minor

#50 Change contrast blocks in button tokens
  src/components/button.ts
Labels: minor

#51 Publish new version 2.5.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#53 Create and export `Skeleton` tokens
  src/components/index.ts
  src/components/skeleton.ts
Labels: minor

#52 Create and export `CountdownBar` tokens
  src/components/countdownbar.ts
  src/components/index.ts
Labels: minor

#54 Publish new version 2.6.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#56 Release new version 2.6.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#57 Create and export Blanket tokens
  src/components/blanket.ts
  src/components/breadcrumbs.ts
  src/components/header.ts
  src/components/index.ts
  src/components/tabs.ts
Labels: minor

#58 Publish new version 2.7.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#59 FIx: adjust breadcrumbs tokens according to the file provided by the designer
  src/components/breadcrumbs.ts
Labels: minor

#60 Publish new version 2.8.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#61 Create and export tokens for `link` component
  src/components/index.ts
  src/components/link.ts
Labels: minor

#62 Publish new version 2.9.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#63 Adjust border and contrast tokens for gray buttons
  src/components/button.ts
Labels: minor

#64 Publish new version 2.10.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#65 Adjust token structure of `tag`, because the las part says `"apparence"` instead of `"appearance"`
  src/components/tag.ts
Labels: bug, patch

#67 Publish new version 2.11.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#68 Update inubekit/foundations to storybook v8
  package-lock.json
  package.json
Labels: dependencies

#69 Create and export `SectionMessage`, `Nav` and `FullScreenNav` tokens
  src/components/fullscreennav.ts
  src/components/index.ts
  src/components/nav.ts
  src/components/sectionmessage.ts
Labels: minor

#70 Publish new version 2.12.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation
